name: Celian Test

on:
  push

jobs:
  celian-git-reinstall:
    runs-on: macos-13
    defaults:
      run:
        shell: bash
    steps:
    - name: Reinstall git
      run: |
        which git
        brew remove --force --ignore-dependencies gettext
        brew reinstall git --ignore-dependencies
        which git
        git --help
        # brew reinstall git --force
        # which git
        # git --help
        # /usr/local/Cellar/git/2.48.0/bin/git --help
        # brew uninstall git --ignore-dependencies --force
        # which git || true
        # git --help || true
        # brew uninstall gettext --ignore-dependencies --force
        # which git || true
        # git --help || true
        # /usr/local/Cellar/git/2.48.0/bin/git --help
        # brew reinstall git --force

  celian-git-build:
    runs-on: macos-13
    defaults:
      run:
        shell: bash
    steps:
    - name: Build git
      run: |
        # TODO: Remove gettext
        brew remove --force --ignore-dependencies gettext

        GIT_VERSION=2.48.1
        curl -LO https://github.com/git/git/archive/refs/tags/v${GIT_VERSION}.tar.gz
        tar -xzf v${GIT_VERSION}.tar.gz
        cd git-${GIT_VERSION}

        make configure
        ./configure
        echo Configured

        make all
        echo Built

        sudo make install
        echo Installed


    # - name: Remove preinstalled environment
    #   run: |
    #     # brew install git

    #     # brew remove --force --ignore-dependencies $(brew list --formula)

    #     # echo CELIAN which git by default
    #     # which git
    #     # rm -rf /usr/bin/git
    #     # brew install git --ignore-dependencies || true

    #     # echo CELIAN which git by brew
    #     # which git
    #     # git --help
    #     # git clone https://github.com/DataDog/datadog-agent.git /tmp/dd-agent
