name: MacOS Agent lint

# Workflow inputs default values are set here instead of using the `defaults` keyword
# so that the `pull_request` event can access them.
#
# Leaving an input empty will use the default value
env:
  DEFAULT_DATADOG_AGENT_REF: 'main'

on:
  pull_request:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      datadog_agent_ref:
        description: 'git ref to target on datadog-agent'
        required: false
      version_cache:
        description: 'Base 64-encoded content of the agent-version.cache file'
        required: false
      python_runtimes:
        description: 'kept for simplicity'
        required: false

jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}

  macos_lint:
    runs-on: macos-11
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v4

    - name: Use XCode 13.2
      run: |
        sudo xcode-select -s /Applications/Xcode_13.2.app

    - name: Cache brew deps
      uses: actions/cache@v3.3.2
      with:
        # Paths to cache:
        # /usr/local/Homebrew - installation folder of Homebrew
        # /usr/local/Cellar - installation folder of Homebrew formulae
        # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
        # /usr/local/lib/python3.9 - Python3 packages installation
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/Frameworks
          /usr/local/bin
          /usr/local/opt
          /usr/local/lib/python3.9
        key: macos-11-build-cache-${{ hashFiles('./scripts/builder_setup.sh') }}

    - name: Clone datadog-agent repository
      env:
        VERSION: ${{ github.event.inputs.datadog_agent_ref || env.DEFAULT_DATADOG_AGENT_REF }}
      run: |
        bash ./scripts/clone_agent.sh
        cd $HOME/go/src/github.com/DataDog/datadog-agent
        export VERSION_CACHE_CONTENT="${{github.event.inputs.version_cache}}"
        if [ ! -z "$VERSION_CACHE_CONTENT" ]; then base64 -d <(echo "$VERSION_CACHE_CONTENT") > ./agent-version.cache; fi

    - name: Set up builder
      run: |
        bash ./scripts/builder_setup.sh lint

    - name: Lint
      env:
        VERSION: ${{ github.event.inputs.datadog_agent_ref || env.DEFAULT_DATADOG_AGENT_REF }}
      run: |
        export GOMODCACHE=~/gomodcache
        mkdir -p $GOMODCACHE
        bash ./scripts/lint.sh

