name: MacOS Agent lint

# Workflow inputs default values are set here instead of using the `defaults` keyword
# so that the `pull_request` event can access them.
#
# Leaving an input empty will use the default value
env:
  DEFAULT_DATADOG_AGENT_REF: 'main'
  DEFAULT_PYTHON_RUNTIMES: '3'
  DDA_NO_DYNAMIC_DEPS: '1'

on:
  pull_request:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      datadog_agent_ref:
        description: 'git ref to target on datadog-agent'
        required: false
      python_runtimes:
        description: 'Included python runtimes in the build'
        required: false
      version_cache:
        description: 'Base 64-encoded content of the agent-version.cache file'
        required: false
      concurrency_key:
        description: 'concurrency key used to cancel running jobs'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.concurrency_key || github.event.inputs.datadog_agent_ref || github.sha }}
  cancel-in-progress: ${{ github.event.inputs.concurrency_key && true || false }}

jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}

  macos_lint:
    runs-on: macos-13
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Use XCode 14.2
      run: |
        sudo xcode-select -s /Applications/Xcode_14.2.app

    - name: Remove preinstalled environment
      run: |
        # The base box ships a few things that can have unwanted effects on the MacOS build.
        # For instance, we compile Python in the pipeline. If Python finds some libraries while
        # it's being compiled, then it will add a dynamic link to them and add some features.
        # In this particular case, Python sees that there is libintl.8.dylib (provided by the gettext brew package)
        # in the default include path, thus links to it. However, that's not something we need, so we don't actually
        # ship that library in the MacOS package. Since we have a feature to make a build fail if we depend on
        # something we don't ship, this made the build fail (see: https://github.com/DataDog/datadog-agent-macos-build/runs/1011733463?check_suite_focus=true).

        # In order to avoid such cases in the future where we use things we didn't expect to, we'd rather
        # start with a "clean" runner with the bare minimum, and only install the brew packages we require.
        brew remove --force --ignore-dependencies $(brew list --formula)

        # Remove existing Python installation as it may otherwise interfere
        sudo rm -rf /Library/Frameworks/Python.framework/Versions/*

    - name: Cache brew deps
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        # Paths to cache:
        # /usr/local/Homebrew - installation folder of Homebrew
        # /usr/local/Cellar - installation folder of Homebrew formulae
        # /usr/local/Frameworks, /usr/local/bin, /usr/local/opt - contain (links to) binaries installed by Homebrew formulae
        # /usr/local/lib/python3.12 - Python3 packages installation
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          /usr/local/Frameworks
          /usr/local/bin
          /usr/local/opt
          /usr/local/lib/python3.12
        key: macos-13-build-cache-${{ hashFiles('./scripts/builder_setup.sh') }}

    - name: Clone datadog-agent repository
      env:
        VERSION: ${{ github.event.inputs.datadog_agent_ref || env.DEFAULT_DATADOG_AGENT_REF }}
      run: |
        bash ./scripts/clone_agent.sh
        cd $HOME/go/src/github.com/DataDog/datadog-agent
        export VERSION_CACHE_CONTENT="${{github.event.inputs.version_cache}}"
        if [ ! -z "$VERSION_CACHE_CONTENT" ]; then echo "$VERSION_CACHE_CONTENT" | base64 -d > ./agent-version.cache; fi

    - name: Set up builder
      run: |
        bash ./scripts/builder_setup.sh

    - name: Lint
      env:
        VERSION: ${{ github.event.inputs.datadog_agent_ref || env.DEFAULT_DATADOG_AGENT_REF }}
        PYTHON_RUNTIMES: ${{ github.event.inputs.python_runtimes || env.DEFAULT_PYTHON_RUNTIMES }}
      run: |
        export GOMODCACHE=~/gomodcache
        mkdir -p $GOMODCACHE
        bash ./scripts/lint.sh
